### ISSUE TITLE
Simplify the download url

### ISSUE THREAD

**Issue by axetroy** [axetroy/cask.rs#27]
Current:

```toml
# Cask.toml
[darwin]
x86_64 = { url = "https://github.com/<username>/<repo>/releases/download/v{version}/darwin_amd64.tar.gz" }
```

If the CASK.TOML file is just a simple point to binary, we can simplify it.

```diff
[darwin]
- x86_64 = { url = "https://github.com/<username>/<repo>/releases/download/v{version}/darwin_amd64.tar.gz" }
+ x86_64 = "https://github.com/<username>/<repo>/releases/download/v{version}/darwin_amd64.tar.gz"
```
