### ISSUE TITLE
feat: extract file from sub-folder in tarball

### ISSUE THREAD

**Issue by axetroy** [axetroy/cask.rs#29]
```toml
[darwin]
x86_64 = { url = "https://github.com/xxx/xxx/releases/download/v{version}/golangci-lint-{version}-darwin-amd64.tar.gz", path = "/path/to/sub/folder" }
```
