### ISSUE TITLE
Running hook in diff platform

### ISSUE THREAD

**Issue by axetroy** [axetroy/cask.rs#39]
Windows:

Cmd or PowerShell

Unix:

sh or shell

#### Command:

```toml
[hook]
preinstall = "echo 'preinstall'"
postinstall = "echo 'postinstall'"
```

#### Windows:

```toml
# running hook in windows with PowerShell
[hook.windows]
preinstall = "echo 'preinstall'"
postinstall = "echo 'postinstall'"
```

#### Unix:

```toml
# running hook in windows with sh
[hook.unix]
preinstall = "echo 'preinstall'"
postinstall = "echo 'postinstall'"
```
