### ISSUE TITLE
support template renderer in Hook script

### ISSUE THREAD

**Issue by axetroy** [axetroy/cask.rs#40]
```toml
[package]
name = "github.com/axetroy/gpm.rs"
bin = "gpm"
versions = ["0.1.12", "0.1.11"]
authors = ["Axetroy <axetroy.dev@gmail.com>"]
keywords = ["gpm", "git", "project", "manager"]
repository = "https://github.com/axetroy/gpm.rs"
description = """
A command line tool, manage your hundreds of repository, written with Rust.
"""

[context]
foo = "bar"

[hook.unix.sh]
preinstall = """
echo "Welcome install {package.name}"
echo "hello {context.foo}"
"""
postinstall = """
echo "{package.bin}@{version} has been installed."
echo "Try runing with fllowing command {package.bin} --help"
"""

[darwin]
x86_64 = "https://github.com/axetroy/gpm.rs/releases/download/v{version}/gpm_darwin_amd64.tar.gz"

```
