### ISSUE TITLE
feat: support build step

### ISSUE THREAD

**Issue by axetroy** [axetroy/cask.rs#41]
```toml
[package]
name = "github.com/axetroy/gpm.rs"
bin = "gpm"
versions = ["0.1.12", "0.1.11"]
authors = ["Axetroy <axetroy.dev@gmail.com>"]
keywords = ["gpm", "git", "project", "manager"]
repository = "https://github.com/axetroy/gpm.rs"
description = """
A command line tool, manage your hundreds of repository, written with Rust.
"""

[build.unix]
sh = """
git clone https://github.com/axetroy/gpm.rs
make
"""
[[build.unix.binary]]
name = "gpm"
path = "./gpm"

[build.windows]
cmd = """
git clone https://github.com/axetroy/gpm.rs
make
"""
[[build.windows.binary]]
name = "gpm"
path = "./gpm.exe"

```

This formula will clone `https://github.com/axetroy/gpm.rs` and then run `make` command.
